# inserimento bancomat
#                  |--------100------| |-----------500---------------|
simulate 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

# PRIMO INSERIMENTO
# inserimento prima cifra corretta
#          |--5--|
simulate 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#inserimento seconda cifra corretta
#          |--5--|
simulate 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#inserimento terza cifra errata
#          |--1--|
simulate 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#clock a vuoto (H -> B)
simulate 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

# SECONDO INSERIMENTO
# inserimento prima cifra corretta
#          |--5--|
simulate 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#inserimento seconda cifra corretta
#          |--5--|
simulate 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#inserimento terza cifra errata
#          |--0--|
simulate 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#inserimento cash richiesto (E -> I)       
#                  |--------100------| |-----------500---------------|
simulate 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0

#delay (I -> A)   cash richiesto < 1/4 cash disponibile 
#                  |--------100------| |-------------1---------------|
simulate 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1


# RISULTATO:
# OUTPUTS: reinserire_cod abilitazione_erog blocco_bancomat ce9 ce8 ce7 ce6 ce5 ce4 ce3 ce2 ce1 ce0 
# NEXT STATE: ct_err1 ct_err0 minore st3 st2 st1 st0
# A 1011
# B 0011
# C 0100
# F 0101
# D 0110
# G 0111
# E 0001
# H 0000
# I 1101
# L 0010

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0000011 # B

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0000100 # C

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0000110 # D

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0100000 # H

#Network simulation:
#Outputs: 1 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0100011 # B

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0100100 # C

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0100110 # D

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0000001 # E

#Network simulation:
#Outputs: 0 0 0 0 0 0 0 0 0 0 0 0 0
#Next state: 0011101 # I

#Network simulation:
#Outputs: 0 1 0 0 0 0 1 1 0 0 1 0 0
#Next state: 0001011 # A